### ISSUE TITLE
Icons in Field text

### ISSUE THREAD

**Issue by NNTin** [Derpolino/discord-webhooks-python#3]
[This is your Discord Webhook Example.](https://i.imgur.com/vPzvV7M.png) It shows how you can have an icon at the very beginning and at the very end.  

[Here is someone putting icons in a Field.](https://i.imgur.com/J3mZAK4.png) How is he doing it?

**Comment by NNTin** [comment]
Is it possible to #link-to-text-channels ~~and ping @everyone through webhook~~? I've been trying without success.

edit: everyone pings work but text channel links dont work.
also you can't ping specific roles even though other people can.

**Comment by harmdhast** [comment]
Where did you found this screenshot https://imgur.com/J3mZAK4 ?
I'm asking the same question.
But It's probably custom icons sadly.

**Comment by NNTin** [comment]
It was custom icons. You can write them via: `<:clockwerk:295657808622256139>`  
I made a discord twitter bot: https://github.com/NNTin/discord-twitter-bot  
https://discord.gg/Dkg79tc go to #info you can see it in action there. (Though that icon only works in my server)
